import Head from 'next/head'
import React from 'react'
import styles from '../../styles/Home.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'

export async function getStaticProps() {
  const mainMenu = [
    {
      description: 'Документация',
      url: '/documentation',
    },
    {
      description: 'О проекте',
      url: '/about',
    },
  ]
  return {
    props: { mainMenu }, // will be passed to the page component as props
  }
}

function Home({ mainMenu }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header mainMenu={mainMenu} />
      <HeroSection />
      <main className={styles.main} />
      <Footer />
    </div>
  )
}

export default Home
